<a href="https://colab.research.google.com/github/NagamaniKoruprolu/Python_Basics/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy - Arrays and Operations

## Learning Objectives
- Understand NumPy arrays and their advantages
- Learn array creation and manipulation
- Master basic array operations
- Practice NumPy mathematical functions


In [2]:
# Import NumPy
import numpy as np

## 1. Creating NumPy Arrays

### Different ways to create arrays:
- From Python lists
- Using NumPy functions
- Special arrays (zeros, ones, identity)

In [10]:
# Creating arrays
# From list
list_array = np.array([1, 2, 3, 4, 5])
print("From list:", list_array)

# Using arange
range_array = np.arange(0, 10, 2)  # Start, stop, step
print("\nUsing arange:", range_array)
range_array = np.arange(0, 15, 3)  # Start, stop, step
print("\nUsing arange:", range_array)


# Using linspace
linear_space = np.linspace(1, 50, 10)  # Start, stop, num of points
print("\nLinspace:", linear_space)

# Special arrays
zeros = np.zeros(3)
ones = np.ones((2, 2))
identity = np.eye(3)

print("\nZeros:", zeros)
print("\nOnes:\n", ones)
print("\nIdentity matrix:\n", identity)


From list: [1 2 3 4 5]

Using arange: [0 2 4 6 8]

Using arange: [ 0  3  6  9 12]

Linspace: [ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]

Zeros: [0. 0. 0.]

Ones:
 [[1. 1.]
 [1. 1.]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2. Array Operations

### Basic operations:
- Arithmetic operations
- Broadcasting
- Element-wise operations

In [13]:
# Array operations

a= np.array([1,2,3])
b= np.array([4,5,6])

# Arithmetic operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# broadcasting
print("add a scalar:", a+2)
print ("multiplat scaler", a*3)

# stastistical operations
print("mean:", np.mean(a))
print(f"sum:{np.sum(a)}")
print(f"max:{np.max(a)}")
print(f"min:{np.min(a)}")

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
add a scalar: [3 4 5]
multiplat scaler [3 6 9]
mean: 2.0
sum:6
max:3
min:1


In [31]:
# Exercise 1: Temprature conversion
def temprature_conversion():
  # create array of celsius tempratures
  celsious = np.linspace(0, 100, 11)

  # Convert to fahrenheit: f= (c * 9/5) +32
  fahrenheit = celsious * (9/5) + 32

  # Create a list of tuples
  list_temp = list(zip(celsious, fahrenheit))
  #print(list_temp)
  return list_temp
print("Temprature conversion table:")
print("Celsius  |  Fahrenheit")
print("-"*20)
for c, f in temprature_conversion():
  print(f"{c:7.1f} | {f:7.1f}")





Temprature conversion table:
Celsius  |  Fahrenheit
--------------------
    0.0 |    32.0
   10.0 |    50.0
   20.0 |    68.0
   30.0 |    86.0
   40.0 |   104.0
   50.0 |   122.0
   60.0 |   140.0
   70.0 |   158.0
   80.0 |   176.0
   90.0 |   194.0
  100.0 |   212.0


In [32]:
# Exercise 2: Matrix Operations
def matrix_calculator():
    # Create two 3x3 matrices
    A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

    B = np.array([[9, 8, 7],
                  [6, 5, 4],
                  [3, 2, 1]])

    print("Matrix A:\n", A)
    print("\nMatrix B:\n", B)

    # Matrix operations
    print("\nMatrix Addition:\n", A + B)
    print("\nMatrix Multiplication:\n", np.dot(A, B))
    print("\nMatrix A Transpose:\n", A.T)
    print("\nDeterminant of A:", np.linalg.det(A))

matrix_calculator()

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix A Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: 0.0


In [41]:
# Exercise 2: Matrix Operations
def matrix_calculator():
    # Create two 3x3 matrices
    A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

    B = np.array([[9, 8, 7],
                  [6, 5, 4],
                  [3, 2, 1]])

    return A, B
a, b = matrix_calculator()
print("Matrix A:\n", a)
print("\nMatrix B:\n", b)
print("\nMatrix Addition:\n", a + b)
print("\nMatrix Multiplication:\n", np.dot(a, b))
print("\nMatrix A Transpose:\n", a.T)
print("\nDeterminant of A:", np.linalg.det(a))

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix A Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: 0.0


. Which function creates an array of evenly spaced numbers?
   - a) np.array()
   - b) np.arange()
   - c) np.zeros()
   - d) np.ones()

2. What is broadcasting in NumPy?
   - a) Converting arrays to lists
   - b) Automatic array shape manipulation for operations
   - c) Broadcasting radio signals
   - d) Printing array elements

3. Which method creates an identity matrix?
   - a) np.identity()
   - b) np.eye()
   - c) np.ones()
   - d) np.diagonal()

4. What is the shape of np.array([1, 2, 3, 4])?n  
   - a) (4,)
   - b) (1, 4)
   - c) (4, 1)
   - d) (1, 1, 4)

5. Which operation is element-wise?
   - a) np.dot()
   - b) np.multiply()
   - c) np.matmul()
   - d) np.cross()

6. How do you find the number of dimensions in a NumPy array?
   - a) array.dim()
   - b) array.ndim
   - c) array.dimensions
   - d) array.shape()

7. What does np.zeros(3) create?
   - a) A 3x3 matrix of zeros
   - b) An array of 3 zeros
   - c) A 3x3x3 cube of zeros
   - d) A single zero repeated 3 times

8. Which method stacks arrays vertically?
   - a) np.hstack()
   - b) np.vstack()
   - c) np.stack()
   - d) np.append()

9. What is the result of np.arange(0, 10, 2)?
   - a) [0, 2, 4, 6, 8]
   - b) [0, 2, 4, 6, 8, 10]
   - c) [2, 4, 6, 8]
   - d) [0, 1, 2, 3, 4]

10. How do you transpose a matrix in NumPy?
    - a) matrix.transpose()
    - b) matrix.T
    - c) Both a and b
    - d) matrix.flip()

Answers: 1-b, 2-b, 3-b, 4-a, 5-b, 6-b, 7-b, 8-b, 9-a, 10-c