<a href="https://colab.research.google.com/github/NagamaniKoruprolu/Python_Basics/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# first payton program
import pandas as pd


In [ ]:
x= 5
name="Jahn"
is_valid=True
print("X=",x)
print("name=",name)
print("is_valid=",is_valid)



X= 5
name= Jahn
is_valid= True


In [ ]:
a=5
b=4
c=a+b;
print("c=",c)


c= 9


In [ ]:
age=18
if age>=18:
  print("audult")
else:
  print("child")


audult


In [ ]:
x=10
a=0
count =0
table =12
while a < x:
 a=a+1
 count=count+1
 print(table,"*",count, "=",table*count)








12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120


In [ ]:
from ast import mod
a=5
print("div:", a%2)

div: 1


In [ ]:
# prompt: code for print even numbers
for a in range(10):
  print(a)



0
1
2
3
4
5
6
7
8
9


In [ ]:
a=[1,2,3,4,5]
for num in a:
  print(num)
names=["aa","bb","cc","dd"]
names.remove("bb")
names.append("ee")
for name in names:
  print(name)


1
2
3
4
5
aa
cc
dd
ee


In [ ]:
# List
import numpy as np
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
print(my_array)
print(my_array.size)


[1 2 3 4 5]
5


In [ ]:
# List
import numpy as np
my_list = [1,2,3,4,5]
#my_array = np.array(my_list)
print(my_array.shape) #help in dealing with rows and columns
result_array = my_array.reshape(5,1)
print(result_array)
print(result_array.shape)
print(np.matrix(my_list))
#print(my_array.size)


(5,)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
[[1 2 3 4 5]]


In [ ]:
# prompt: give me slicing examples



# NumPy array slicing
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(my_array[1:5])  # Output: [2 3 4]
print(my_array[3:4])  # Output: [1 2 3 4]
print(my_array[4:])  # Output: [5 6 7 8]
print(my_array[-3:]) # Output: [6 7 8]
print(my_array[::2]) # Output: [1 3 5 7]


# Pandas DataFrame slicing
import pandas as pd # Import pandas and assign it to the alias 'pd'
data = {'col1': [1, 2, 3, 4, 5], 'col2': [6, 7, 8, 9, 10]}
df = pd.DataFrame(data)

#print(df[1:4]) # select rows 1 to 3
print(df.loc[0:2, 'col1']) # select col1 for row 0 to 2
#print(df.iloc[0:2, 0]) # select col1 for row 0 to 1



[2 3 4 5]
[4]
[5 6 7 8]
[6 7 8]
[1 3 5 7]
0    1
1    2
2    3
Name: col1, dtype: int64


In [ ]:
import sys

print(sys.version)

3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


In [1]:
# Dictionary of AI tools and their applications
ai_tools = {
    'ChatGPT': 'Natural Language Processing',
    'Tesla Autopilot': 'Computer Vision & Autonomous Driving',
    'Netflix Recommendations': 'Recommendation Systems',
    'Gmail Spam Filter': 'Classification',
    'Alexa': 'Speech Recognition'
}

# Print the AI tools and their applications
for tool, application in ai_tools.items():
    print(f"{tool}: {application}")

ChatGPT: Natural Language Processing
Tesla Autopilot: Computer Vision & Autonomous Driving
Netflix Recommendations: Recommendation Systems
Gmail Spam Filter: Classification
Alexa: Speech Recognition
